version: '3.8'
# purpose
# run development environment

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Zldzhd12!
      POSTGRES_DB: animallens
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init_tables.sql:/docker-entrypoint-initdb.d/0_init_tables.sql:ro
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/1_init.sql:ro
# backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      
    env_file:
      - .env.development
    environment:
      ENVIRONMENT: development
      
    depends_on:
      - postgres
# frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8000"
    command: sh -c "pnpm install && pnpm dev"
    depends_on:
      - backend
# volumes
volumes:
  postgres_data:
